# Generated by Django 4.2.29 on 2026-04-04 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('nivel', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=20)),
                ('probabilidad', models.FloatField(blank=True, null=True)),
                ('impacto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('calculado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'joz_riesgos',
                'ordering': ['-calculado_en'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(db_index=True, max_length=100)),
                ('tipo', models.CharField(blank=True, default='', max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha', models.DateField(db_index=True)),
                ('cliente', models.CharField(blank=True, default='', max_length=300)),
                ('estado', models.CharField(blank=True, default='pendiente', max_length=100)),
                ('raw_data', models.JSONField(default=dict)),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'joz_transacciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_revision', 'En revisión'), ('resuelta', 'Resuelta'), ('descartada', 'Descartada')], default='abierta', max_length=20)),
                ('score_anomalia', models.FloatField(blank=True, null=True)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('transaccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='joz.transaccion')),
            ],
            options={
                'db_table': 'joz_alertas',
                'ordering': ['-generado_en'],
            },
        ),
    ]
