# Generated by Django 4.2.29 on 2026-04-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('fecha_consulta', models.DateField(help_text='Fecha de los movimientos consultados')),
                ('almacen', models.IntegerField(default=0, help_text='0 = todos los almacenes')),
                ('filas_recibidas', models.IntegerField(default=0)),
                ('filas_insertadas', models.IntegerField(default=0)),
                ('filas_error', models.IntegerField(default=0)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('mensaje', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'joz_etl_log',
                'ordering': ['-iniciado_en'],
            },
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha', '-hora_minutos']},
        ),
        migrations.AddField(
            model_name='transaccion',
            name='almacen',
            field=models.IntegerField(blank=True, db_index=True, help_text='Código de almacén (1-30)', null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción libre del movimiento (detalle del empeño)'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='entrada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Monto de entrada (campo 'entrada' de la API)", max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='hora_minutos',
            field=models.IntegerField(blank=True, help_text='Minutos desde medianoche (hora.totalMinutes de la API)', null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='id_externo',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del movimiento en SuperEfectivo', null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='numero_identificacion',
            field=models.CharField(blank=True, default='', help_text='Cédula/ID del cliente', max_length=50),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='salida',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Monto de salida (campo 'salida' de la API)", max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuario_cajero',
            field=models.CharField(blank=True, default='', help_text='Usuario cajero que registró el movimiento', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cliente',
            field=models.CharField(blank=True, default='', help_text='Nombre completo del cliente', max_length=300),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(blank=True, default='cargado', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Valor total del movimiento', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='referencia',
            field=models.CharField(db_index=True, help_text='nrodocumento de la API', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(blank=True, default='', help_text='Aporte o Retiro', max_length=100),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['fecha', 'almacen'], name='joz_transac_fecha_e8aff9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['tipo', 'fecha'], name='joz_transac_tipo_572fd3_idx'),
        ),
    ]
