# Generated by Django 4.2 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joz', '0002_etllog_alter_transaccion_options_transaccion_almacen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDeteccion',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled_alto_valor', models.BooleanField(default=True)),
                ('enabled_multiples_transacciones', models.BooleanField(default=True)),
                ('enabled_horario_inusual', models.BooleanField(default=True)),
                ('enabled_descuentos_excesivos', models.BooleanField(default=False)),
                ('monto_maximo', models.DecimalField(decimal_places=2, default=10000000, max_digits=18)),
                ('descuento_maximo_pct', models.IntegerField(default=50)),
                ('transacciones_por_hora', models.IntegerField(default=20)),
                ('score_riesgo_min', models.IntegerField(default=75)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'joz_config_deteccion',
            },
        ),
    ]
