# Generated by Django 4.2.30 on 2026-04-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joz', '0003_configdeteccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='etllog',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('programado', 'Programado')], db_index=True, default='manual', max_length=20),
        ),
    ]
