# Generated by Django 6.0.4 on 2026-04-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joz', '0004_add_origen_etllog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configdeteccion',
            name='descuento_maximo_pct',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='enabled_alto_valor',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='enabled_descuentos_excesivos',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='enabled_horario_inusual',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='enabled_multiples_transacciones',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='monto_maximo',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='score_riesgo_min',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='transacciones_por_hora',
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='cajero_ratio',
            field=models.FloatField(default=2.0, help_text='Factor mínimo sobre promedio para alertar (ej: 2.0 = 2x)'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='cajero_ratio_alta',
            field=models.FloatField(default=3.0, help_text='Factor para severidad alta'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='cuadre_umbral_alta',
            field=models.DecimalField(decimal_places=2, default=50000, help_text='Diferencia mínima (USD) para severidad alta', max_digits=18),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='cuadre_umbral_media',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Diferencia mínima (USD) para severidad media', max_digits=18),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='desbalance_tolerancia',
            field=models.FloatField(default=0.02, help_text='Tolerancia para desbalance (0.02 = 2%)'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='desbalance_umbral_alta',
            field=models.FloatField(default=5.0, help_text='% de diferencia para severidad alta'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='enabled_concentracion_cajero',
            field=models.BooleanField(default=True, help_text='Detectar cajeros con volumen anómalo'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='enabled_cuadre_caja',
            field=models.BooleanField(default=True, help_text='Detectar desviación de balance diario por almacén'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='enabled_desbalance_cruzado',
            field=models.BooleanField(default=True, help_text='Detectar diferencia >umbral en pares aporte/retiro cruzados'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='enabled_desviacion_monto',
            field=models.BooleanField(default=True, help_text='Detectar montos anómalos por Z-score'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='enabled_duplicidad_cruzada',
            field=models.BooleanField(default=True, help_text='Detectar doccruce duplicados en retiros'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='enabled_horario_atipico',
            field=models.BooleanField(default=True, help_text='Detectar transacciones fuera de horario operativo'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='enabled_partida_doble',
            field=models.BooleanField(default=True, help_text='Detectar movimientos cruzados sin contraparte'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='enabled_reincidencia_cajero',
            field=models.BooleanField(default=True, help_text='Detectar cajeros con alta tasa de anomalías'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='enabled_reincidencia_tienda',
            field=models.BooleanField(default=True, help_text='Detectar almacenes con alta tasa de anomalías'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='enabled_score_transaccion',
            field=models.BooleanField(default=True, help_text='Score compuesto por transacción (monto+hora+concentración)'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='hora_fin',
            field=models.IntegerField(default=21, help_text='Hora de fin operativo (0-23)'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='hora_inicio',
            field=models.IntegerField(default=6, help_text='Hora de inicio operativo (0-23)'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='horario_monto_boost',
            field=models.DecimalField(decimal_places=2, default=3000, help_text='Monto (USD) que eleva la severidad en horario atípico', max_digits=18),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='partida_doble_tolerancia',
            field=models.FloatField(default=0.02, help_text='Tolerancia de diferencia entre pares (0.02 = 2%)'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='reincidencia_cajero_pct',
            field=models.FloatField(default=3.0, help_text='Tasa mínima (%) de alertas/transacciones para alertar'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='reincidencia_tienda_pct',
            field=models.FloatField(default=5.0, help_text='Tasa mínima (%) de alertas/transacciones para alertar'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='score_umbral',
            field=models.FloatField(default=0.5, help_text='Score mínimo (0-1) para generar alerta'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='score_umbral_alta',
            field=models.FloatField(default=0.8, help_text='Score para severidad alta'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='zscore_alta',
            field=models.FloatField(default=3.0, help_text='Z-score para severidad alta'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='zscore_critica',
            field=models.FloatField(default=4.0, help_text='Z-score para severidad crítica'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='zscore_media',
            field=models.FloatField(default=2.0, help_text='Z-score mínimo para generar alerta (severidad media)'),
        ),
    ]
