# Generated by Django 4.2.30 on 2026-04-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joz', '0005_config_deteccion_reglas'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaccion',
            constraint=models.UniqueConstraint(condition=models.Q(('id_externo__isnull', False)), fields=('id_externo',), name='uq_transaccion_id_externo'),
        ),
    ]
