# Generated by Django 6.0.4 on 2026-04-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joz', '0006_dedup_id_externo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configdeteccion',
            name='cuadre_umbral_alta',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='cuadre_umbral_media',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='desbalance_tolerancia',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='desbalance_umbral_alta',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='enabled_cuadre_caja',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='enabled_desbalance_cruzado',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='enabled_duplicidad_cruzada',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='enabled_partida_doble',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='enabled_reincidencia_cajero',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='enabled_reincidencia_tienda',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='enabled_score_transaccion',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='partida_doble_tolerancia',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='reincidencia_cajero_pct',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='reincidencia_tienda_pct',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='score_umbral',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='score_umbral_alta',
        ),
        migrations.AlterField(
            model_name='configdeteccion',
            name='horario_monto_boost',
            field=models.DecimalField(decimal_places=2, default=3000, help_text='Monto (COP) que eleva la severidad en horario atípico', max_digits=18),
        ),
    ]
