# Generated by Django 4.2.30 on 2026-04-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joz', '0007_simplificar_config_3_reglas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configdeteccion',
            name='enabled_horario_atipico',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='configdeteccion',
            name='horario_monto_boost',
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='enabled_fraccionamiento',
            field=models.BooleanField(default=True, help_text='Detectar clientes con muchas transacciones pequeñas en un día'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='fraccionamiento_min_txns',
            field=models.IntegerField(default=5, help_text='Mínimo de transacciones/día para considerar fraccionamiento'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='fraccionamiento_min_txns_alta',
            field=models.IntegerField(default=10, help_text='Transacciones/día para severidad alta'),
        ),
        migrations.AddField(
            model_name='configdeteccion',
            name='fraccionamiento_min_txns_critica',
            field=models.IntegerField(default=20, help_text='Transacciones/día para severidad crítica'),
        ),
    ]
