# Generated by Django 4.2.30 on 2026-05-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joz', '0011_drop_configdeteccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regladeteccion',
            name='tipo_motor',
            field=models.CharField(choices=[('zscore', 'Z-Score (desviación estadística)'), ('conteo', 'Conteo (agrupación y umbral)'), ('ratio', 'Ratio (proporción vs promedio)'), ('contrapartida', 'Contrapartida (matching salida↔entrada)')], help_text='Motor de evaluación que usa esta regla', max_length=20),
        ),
    ]
