# Generated by Django 4.2.30 on 2026-05-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joz', '0013_seed_regla_contrapartida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riesgo',
            name='calculado_en',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
